volumes: 
  sqldb-data:
    
services: 
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=localDevPassw0rd!
    ports:
      - 1433:1433
    volumes:
      - sqldb-data:/var/opt/mssql
    container_name: piniq-database
    