// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pinball.Api.Data;

namespace Pinball.Api.Data.Migrations
{
    [DbContext(typeof(PinballDbContext))]
    [Migration("20210206220625_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Pinball.Api.Data.Entities.OpdbCatalogSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Imported")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineGroupJsonResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineJsonResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Published")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CatalogSnapshots");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.OpdbChangelog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewOpdbId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdbId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpdbChangelogs");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IpdbId")
                        .HasColumnType("int");

                    b.Property<string>("MachineGroupId")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<short>("PlayerCount")
                        .HasColumnType("smallint");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MachineGroupId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TypeId");

                    b.ToTable("PinballMachines");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PinballFeatures");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineFeatureMapping", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("FeatureId", "MachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("PinballMachineFeatureMapping");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PinballMachineGroups");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PinballKeywords");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineKeywordMapping", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("KeywordId", "MachineId");

                    b.HasIndex("KeywordId");

                    b.HasIndex("MachineId");

                    b.ToTable("PinballMachineKeywordMapping");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PinballManufacturers");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PinballTypes");

                    b.HasData(
                        new
                        {
                            Id = "ss",
                            Name = "Solid-State"
                        },
                        new
                        {
                            Id = "em",
                            Name = "Electro-Mechanical"
                        },
                        new
                        {
                            Id = "me",
                            Name = "Mechanical"
                        },
                        new
                        {
                            Id = "dmd",
                            Name = "Dot-Matrix Display"
                        });
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachine", b =>
                {
                    b.HasOne("Pinball.Api.Data.Entities.PinballMachineGroup", "MachineGroup")
                        .WithMany("Machines")
                        .HasForeignKey("MachineGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pinball.Api.Data.Entities.PinballMachineManufacturer", "Manufacturer")
                        .WithMany("Machines")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pinball.Api.Data.Entities.PinballMachineType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MachineGroup");

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineFeatureMapping", b =>
                {
                    b.HasOne("Pinball.Api.Data.Entities.PinballMachineFeature", "Feature")
                        .WithMany("Mappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pinball.Api.Data.Entities.PinballMachine", "Machine")
                        .WithMany("FeatureMappings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineKeywordMapping", b =>
                {
                    b.HasOne("Pinball.Api.Data.Entities.PinballMachineKeyword", "Keyword")
                        .WithMany("Mappings")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pinball.Api.Data.Entities.PinballMachine", "Machine")
                        .WithMany("KeywordMappings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachine", b =>
                {
                    b.Navigation("FeatureMappings");

                    b.Navigation("KeywordMappings");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineFeature", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineGroup", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineKeyword", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Pinball.Api.Data.Entities.PinballMachineManufacturer", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
