@Pinball.Api_HostAddress = https://localhost:8001
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvZ2lkIjoiVGVzdElEIiwib2dpc3MiOiJTZWxmIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJodHRwczovL2xvY2FsaG9zdDo4MDAxIl0sIm5iZiI6MTcxOTM2OTUzMCwiZXhwIjoxNzE5MzcxMzMwLCJpc3MiOiJwaW5pcS1kZXYifQ.oERAUt4C-QizHCcRDrtsf5IQ3rG2xrLWOG7BE5cF49s

GET {{Pinball.Api_HostAddress}}/login/TestToken?testKey=thisIsATest

###

GET {{Pinball.Api_HostAddress}}/api/admin/PinballMachineCatalogSnapshots
Authorization: Bearer {{AccessToken}}

###

GET {{Pinball.Api_HostAddress}}/api/admin/PinballMachineCatalogSnapshots/1
Authorization: Bearer {{AccessToken}}

###

POST {{Pinball.Api_HostAddress}}/api/admin/PinballMachineCatalogSnapshots/Import
Authorization: Bearer {{AccessToken}}